# Generated by Django 4.2.9 on 2024-02-25 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_settings_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            2,
                            25,
                            15,
                            41,
                            47,
                            353507,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter",
                "verbose_name_plural": "Newsletter",
            },
        ),
    ]
