# Generated by Django 4.2.9 on 2024-01-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
