# Generated by Django 4.2.9 on 2024-02-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_alter_propertybook_children_alter_propertybook_guest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertybook",
            name="children",
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
        migrations.AlterField(
            model_name="propertybook",
            name="guest",
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
