# Generated by Django 4.2.9 on 2024-02-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_alter_propertybook_children_alter_propertybook_guest"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
    ]
